"""new fields in user model

Revision ID: 882a29d036f2
Revises: a02b3a980c2c
Create Date: 2020-04-24 09:20:04.538089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882a29d036f2'
down_revision = 'a02b3a980c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
